name: CMake on a single platform
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Vulkan SDK
      run: mkdir vulkan
        wget -qO- https://sdk.lunarg.com/sdk/download/1.3.296.0/linux/vulkansdk-linux-x86_64-1.3.296.0.tar.xz | tar xJ -C $HOME/vulkan
        export PATH=$VULKAN_SDK/bin:$PATH
        export LD_LIBRARY_PATH=$VULKAN_SDK/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
        export VK_LAYER_PATH=$VULKAN_SDK/share/vulkan/explicit_layer.d
        sudo cp -r $VULKAN_SDK/include/vulkan/ /usr/local/include/
        sudo cp -P $VULKAN_SDK/lib/libvulkan.so* /usr/local/lib/
        sudo cp $VULKAN_SDK/lib/libVkLayer_*.so /usr/local/lib/
        sudo mkdir -p /usr/local/share/vulkan/explicit_layer.d
        sudo cp $VULKAN_SDK/share/vulkan/explicit_layer.d/VkLayer_*.json /usr/local/share/vulkan/explicit_layer.d
        vulkaninfo

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
